<?
$keys = array("CATALOGUE_ID", "PARENT_ID", "SLUG", "NAME", "CATNAME", "REALCATNAME", "URL", "TITLE", "DESCRIPTION", "METADESC", "METAKEYW", "ICON_IMAGE", "COLOR", "IMG_TITLE", "COUNT_", "LINKED_COUNT_", "OLDCODE", "STATUS", "REALSTATUS", "ORDERING", "EXPORT_ID", "WHOLESALE");

$values = array(
	array(233, 1, 'uksusy', 'Уксусы', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, '51201', 1, 0, 1, 0, 0),
);